apiVersion: batch/v1
kind: Job
metadata:
  name: JOB_NAME
spec:
  completions: JOB_COMPLETIONS
  parallelism: JOB_SCALE
  template:
    spec:
      initContainers:
        - name: php-api-client-data
          image: API_CLIENT_IMAGE
          imagePullPolicy: Always
          command: ['sh', '-c', 'mkdir -p /home/jenkins/php-api-client && cp -Rp /data/. /home/jenkins/php-api-client']
          volumeMounts:
            - { mountPath: /home/jenkins, name: pim }
        - name: pim-community-dev-data
          image: PIM_IMAGE
          imagePullPolicy: Always
          command: ['sh', '-c', 'mkdir -p /home/jenkins/pim && cp -Rp /data/. /home/jenkins/pim']
          volumeMounts:
            - { mountPath: /home/jenkins, name: pim }
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "akeneo"
        - "akeneo.dev"
        - "akeneo-pim"
        - "mysql"
      containers:
        - name: mysql
          image: eu.gcr.io/akeneo-ci/mysql:5.5
          imagePullPolicy: Always
          env:
            - { name: MYSQL_ROOT_PASSWORD, value: root }
            - { name: MYSQL_USER, value: akeneo_pim }
            - { name: MYSQL_PASSWORD, value: akeneo_pim }
            - { name: MYSQL_DATABASE, value: akeneo_pim }
          readinessProbe:
            timeoutSeconds: 5
            initialDelaySeconds: 5
            failureThreshold: 30
            exec:
              command: ["mysql", "-proot", "-h", "127.0.0.1", "-e", "SELECT 1"]
          volumeMounts:
            - { name: tmp-pod, mountPath: /tmp/pod, readOnly: true }
          resources:
            requests: {cpu: "100m", memory: "700Mi"}
        - name: php-api
          image: akeneo/apache-php:php-PHP_API_VERSION
          command: ["/bin/bash", "-c"]
          args:
            - |
              tail -f /dev/null &
              CHILD_PID=$!
              (while true; do if [[ -f "/tmp/pod/main-terminated" ]]; then kill $CHILD_PID; fi; sleep 1; done) &
              wait $CHILD_PID
              if [[ -f "/tmp/pod/main-terminated" ]]; then exit 0; fi
          workingDir: /home/jenkins/php-api-client
          volumeMounts:
            - { name: pim, mountPath: /home/jenkins }
            - { name: tmp-pod, mountPath: /tmp/pod, readOnly: true }
            - { name: docker-socket, mountPath: /var/run/docker.sock }
            - { name: docker-exec, mountPath: /usr/bin/docker }
          resources:
            requests: {cpu: "300m", memory: "300Mi"}
        - name: php
          image: akeneo/apache-php:php-5.6
          command: ["/bin/bash", "-c"]
          args:
            - |
              sudo /usr/local/bin/apache-foreground &
              CHILD_PID=$!
              (while true; do if [[ -f "/tmp/pod/main-terminated" ]]; then sudo kill -9 $CHILD_PID; fi; sleep 1; done) &
              wait $CHILD_PID
              if [[ -f "/tmp/pod/main-terminated" ]]; then exit 0; fi
          workingDir: /home/jenkins/pim
          volumeMounts:
            - { name: pim, mountPath: /home/jenkins }
            - { name: tmp-pod, mountPath: /tmp/pod, readOnly: true }
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/apache2ctl", "stop"]
          resources:
            requests: {cpu: "500m", memory: "750Mi"}
        - name: pubsub
          image: eu.gcr.io/akeneo-ci/gcloud:1.0
          imagePullPolicy: Always

          command: ["/bin/sh", "-c"]
          args:
            - |
              trap "touch /tmp/pod/main-terminated" EXIT
              gcloud.phar pubsub:message:consume SUBSCRIPTION_NAME RESULT_TOPIC
          env:
            - { name: REDIS_URI, value: "tcp://redis.jenkins:6379" }
            - { name: POD_NAME, valueFrom: { fieldRef: { fieldPath: metadata.name } } }
            - { name: NAMESPACE, valueFrom: { fieldRef: { fieldPath: metadata.namespace } } }
          volumeMounts:
            - { name: pim, mountPath: /home/jenkins }
            - { name: tmp-pod, mountPath: /tmp/pod }
          resources:
            requests: {cpu: "100m", memory: "100Mi"}
      volumes:
        - { name: pim, emptyDir: {medium: Memory}}
        - { name: tmp-pod, emptyDir: {medium: Memory}}
        - { name: mysql, emptyDir: {medium: Memory}}
        - { name: docker-socket, hostPath: { path: /var/run/docker.sock }}
        - { name: docker-exec, hostPath: { path: /usr/bin/docker }}
      restartPolicy: Never
